### ISSUE TITLE
Solidify pin config/pin list for project

### ISSUE THREAD

**Issue by cbwolfe94** [Conner-Mico/SPI-TFT-Screen-Project#27]
I2C bus for temp sensor
I2C bus for display touch screen driver
SPI bus for display driver
SAI(I2S) for potential speaker
SDMMC for SD Card
SPI bus for potential WiFi chip
GPIO for various functions like LEDs, chip selects, etc.

You should have enough pins for everything

**Comment by mandelMakes** [comment]
Created a first draft pinout and submitted a PR for the documentation update branch.
